name: tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: ["7.4", "8.0", "8.1", "8.2", "8.3"]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - php: "7.4"
            dependency-version: prefer-lowest
            laravel: "^8.83.27"
            testbench: "^6.0"
          - php: "7.4"
            dependency-version: prefer-stable
            laravel: "^8.83.27"
            testbench: "^6.0"
          - php: "8.0"
            dependency-version: prefer-lowest
            laravel: "^8.83.27"
            testbench: "^6.0"
          - php: "8.0"
            dependency-version: prefer-stable
            laravel: "^9.0"
            testbench: "^7.0"
          - php: "8.1"
            dependency-version: prefer-lowest
            laravel: "^8.83.27"
            testbench: "^6.0"
          - php: "8.1"
            dependency-version: prefer-stable
            laravel: "^10.0"
            testbench: "^8.0"
          - php: "8.2"
            dependency-version: prefer-lowest
            laravel: "^10.0"
            testbench: "^8.0"
          - php: "8.2"
            dependency-version: prefer-stable
            laravel: "^11.0"
            testbench: "^9.0"
          - php: "8.3"
            dependency-version: prefer-lowest
            laravel: "^11.0"
            testbench: "^9.0"
          - php: "8.3"
            dependency-version: prefer-stable
            laravel: "^12.0"
            testbench: "^10.0"

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Setup Problem Matches
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer config --no-interaction audit.block-insecure false
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
