name: tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
          # PHP 7.4 with Laravel 8
          - php: "7.4"
            laravel: "^8.83.27"
            testbench: "^6.0"
            dependency-version: prefer-lowest
          - php: "7.4"
            laravel: "^8.83.27"
            testbench: "^6.0"
            dependency-version: prefer-stable
          # PHP 8.0 with Laravel 8 and 9
          - php: "8.0"
            laravel: "^8.83.27"
            testbench: "^6.0"
            dependency-version: prefer-lowest
          - php: "8.0"
            laravel: "^9.0"
            testbench: "^7.0"
            dependency-version: prefer-stable
          # PHP 8.1 with Laravel 8, 9, and 10
          - php: "8.1"
            laravel: "^8.83.27"
            testbench: "^6.0"
            dependency-version: prefer-lowest
          - php: "8.1"
            laravel: "^10.0"
            testbench: "^8.0"
            dependency-version: prefer-stable
          # PHP 8.2 with Laravel 10 and 11
          - php: "8.2"
            laravel: "^10.0"
            testbench: "^8.0"
            dependency-version: prefer-lowest
          - php: "8.2"
            laravel: "^11.0"
            testbench: "^9.0"
            dependency-version: prefer-stable
          # PHP 8.3 with Laravel 11 and 12
          - php: "8.3"
            laravel: "^11.0"
            testbench: "^9.0"
            dependency-version: prefer-lowest
          - php: "8.3"
            laravel: "^12.0"
            testbench: "^10.0"
            dependency-version: prefer-stable

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Setup Problem Matches
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
